services:
  mongo:
    image: mongo:7
    container_name: facturacion-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: facturacion-backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    ports:
      - "4000:4000"

#  frontend:
#    build: ./frontend
#    container_name: facturacion-frontend
#    restart: always
#    env_file:
#      - ./frontend/.env
#    depends_on:
#      - backend
#    ports:
#      - "5173:5173"

volumes:
  mongo_data: